package com.agentichat.model.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Represents a single chat session between a user and the AI agent.
 *
 * One conversation has many messages (1:N relationship).
 *
 * WHY UUID AS PRIMARY KEY?
 * Auto-increment integers (1, 2, 3...) are predictable — a user could guess
 * other users' conversation IDs and access them. UUIDs are random and
 * unguessable. Always use UUIDs for user-facing IDs in production.
 *
 * WHY @Table with indexes?
 * Without an index, "find all conversations for user X" scans the ENTIRE table.
 * An index on user_id makes that query instant regardless of table size.
 */
@Entity
@Table(
    name = "conversations",
    indexes = {
        @Index(name = "idx_conversations_user_id", columnList = "user_id"),
        @Index(name = "idx_conversations_created_at", columnList = "created_at")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Conversation {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // The user who owns this conversation.
    // In a full app this would be a FK to a users table.
    // We keep it simple here as a plain string (userId or username).
    @Column(name = "user_id", nullable = false)
    private String userId;

    // Optional human-readable title, e.g. "Trip planning for Paris"
    // Could be auto-generated by the AI on the first message.
    @Column(name = "title", length = 255)
    private String title;

    // Soft delete: instead of actually deleting a row (which is irreversible
    // and causes FK constraint issues), we just mark it as deleted.
    // Queries filter with WHERE is_deleted = false.
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private boolean deleted = false;

    // Hibernate automatically sets this on INSERT
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // Hibernate automatically updates this on every UPDATE
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ONE conversation → MANY messages
    // mappedBy = "conversation" means the FK is on the Message side (message.conversation_id)
    // cascade = ALL means if we save/delete a Conversation, all its Messages follow
    // orphanRemoval = true means if we remove a Message from this list, it's deleted from DB
    // FetchType.LAZY = don't load messages until explicitly accessed (performance critical!)
    @OneToMany(
        mappedBy = "conversation",
        cascade = CascadeType.ALL,
        orphanRemoval = true,
        fetch = FetchType.LAZY
    )
    @OrderBy("createdAt ASC")           // Always ordered oldest-first
    @Builder.Default
    private List<Message> messages = new ArrayList<>();

    // Convenience method — keeps the bidirectional relationship consistent
    public void addMessage(Message message) {
        messages.add(message);
        message.setConversation(this);
    }
}