package com.agentichat.model.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * A single message in a conversation.
 *
 * Messages have a ROLE — this is a core concept in all LLM APIs:
 *
 *   USER      = message typed by the human
 *   ASSISTANT = response generated by the AI
 *   SYSTEM    = invisible instructions that set the AI's behavior
 *              (e.g., "You are a helpful assistant that only answers about cooking")
 *   TOOL      = the result returned by a tool call (fed back into the agent loop)
 *
 * When we send conversation history to the LLM, we send ALL messages in order
 * with their roles. This is how the LLM "remembers" the conversation.
 */
@Entity
@Table(
    name = "messages",
    indexes = {
        @Index(name = "idx_messages_conversation_id", columnList = "conversation_id"),
        @Index(name = "idx_messages_created_at", columnList = "created_at")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // FK → conversations.id
    // LAZY fetch: loading a Message does NOT auto-load the whole Conversation
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "conversation_id", nullable = false)
    private Conversation conversation;

    // The role of the message sender
    @Enumerated(EnumType.STRING)    // Store as "USER", "ASSISTANT" etc, not 0, 1, 2
    @Column(name = "role", nullable = false, length = 20)
    private MessageRole role;

    // The actual text content of the message.
    // TEXT in Postgres = unlimited length (unlike VARCHAR which has a max)
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    // Total tokens used for this message turn (input + output).
    // Useful for cost tracking and enforcing per-user limits.
    @Column(name = "token_count")
    private Integer tokenCount;

    // Which LLM model generated this response (e.g. "gpt-4o", "claude-opus-4-6")
    // Stored for auditing — if you switch models, you can see which messages
    // were generated by which model.
    @Column(name = "model_used", length = 100)
    private String modelUsed;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // ONE message → MANY agent steps
    // An ASSISTANT message may have gone through multiple reasoning steps
    // before producing the final content.
    @OneToMany(
        mappedBy = "message",
        cascade = CascadeType.ALL,
        orphanRemoval = true,
        fetch = FetchType.LAZY
    )
    @OrderBy("stepNumber ASC")
    @Builder.Default
    private List<AgentStep> agentSteps = new ArrayList<>();

    /**
     * Message roles — mirrors the OpenAI/Anthropic API roles exactly.
     * Using an enum (not a plain String) prevents typos and gives compile-time safety.
     */
    public enum MessageRole {
        USER,        // Human's message
        ASSISTANT,   // AI's response
        SYSTEM,      // Invisible system prompt
        TOOL         // Tool execution result fed back to the agent
    }
}